test:
  adapter: postgresql
  encoding: unicode
  database: wp_test
  username: postgres
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  database: wp_development
  username: postgres
  pool: 5
